In [23]:
import numpy as p

In [2]:
d2 = n.array([[1,2,3,4],[4,5,6,7]])

In [4]:
d2.dtype

dtype('int32')

In [5]:
type(d2)

numpy.ndarray

In [6]:
d2.itemsize

4

In [7]:
n.power(d2,2)

array([[ 1,  4,  9, 16],
       [16, 25, 36, 49]], dtype=int32)

In [8]:
n.log(d2)

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015]])

In [13]:
e=n.exp(d2)
e

array([[   2.71828183,    7.3890561 ,   20.08553692,   54.59815003],
       [  54.59815003,  148.4131591 ,  403.42879349, 1096.63315843]])

In [14]:
n.round_(e)

array([[   3.,    7.,   20.,   55.],
       [  55.,  148.,  403., 1097.]])

In [15]:
n.add(d2,4)

array([[ 5,  6,  7,  8],
       [ 8,  9, 10, 11]])

In [16]:
n.multiply(d2,3)

array([[ 3,  6,  9, 12],
       [12, 15, 18, 21]])

In [17]:
n.mean(d2)

4.0

In [18]:
n.median(d2)

4.0

In [19]:
from scipy import stats as s

In [20]:
n.average(d2)

4.0