In [1]:
import numpy as np

In [58]:
a=np.array([1,2,2,3])
b=np.array([1,0,1])
c=np.array([10,20,30,40])

In [9]:
q=["Manish",1,2,True]
q

['Manish', 1, 2, True]

In [7]:
z=np.array([2,"manish",True,1])

In [8]:
z

array(['2', 'manish', 'True', '1'], dtype='<U11')

In [10]:
min(a)

1

In [11]:
max(b)

1

In [20]:
np.add(a,c)

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [21]:
np.power(a,b)

array([1, 1, 3], dtype=int32)

In [22]:
np.log(a)

array([0.        , 0.69314718, 1.09861229])

In [23]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [24]:
g=np.array([1.233,2.0,3,4.123])

In [25]:
g

array([1.233, 2.   , 3.   , 4.123])

In [26]:
np.round_(g,1)

array([1.2, 2. , 3. , 4.1])

In [32]:
type(a)

numpy.ndarray

In [33]:
a.shape

(3,)

In [34]:
a.ndim

1

In [39]:
h=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

In [40]:
h.ndim

3

In [41]:
h

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [48]:
p=np.array(42)

In [49]:
p.ndim

0

In [50]:
h.shape

(2, 2, 2)

In [51]:
h.size

8

In [52]:
a

array([1, 2, 3])

In [53]:
np.mean(a)

2.0

In [54]:
np.median(a)

2.0

In [56]:
from scipy import stats as s

In [59]:
s.mode(a)

ModeResult(mode=array([2]), count=array([2]))

In [60]:
np.average(a)

2.0

In [61]:
np.std(a)

0.7071067811865476

In [62]:
np.var(a)

0.5

In [63]:
a

array([1, 2, 2, 3])

In [64]:
np.exp(a)

array([ 2.71828183,  7.3890561 ,  7.3890561 , 20.08553692])

In [65]:
z=np.array([5,4,3,2,1])

In [66]:
np.exp(z)

array([148.4131591 ,  54.59815003,  20.08553692,   7.3890561 ,
         2.71828183])

In [68]:
n=np.array([1,1.2,1.8,2.0])

In [70]:
np.exp(n)

array([2.71828183, 3.32011692, 6.04964746, 7.3890561 ])